#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ ! -f vendor/autoload.php ]; then
    composer install
fi

# if [ $# -gt 0 ]; then
#     exec gosu $WWWUSER "$@"
# else
#     exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
# fi
